---
title: "Progress Memo 1"
subtitle: |
  | Final Project 
  | Data Science 2 with R (STAT 301-2)
author: "Ada Liu"
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
reference-location: margin
citation-location: margin
---

::: {.callout-tip icon=false}

## Github Repo Link

[https://github.com/stat301-2-2024-winter/final-project-2-adacliu.git](https://github.com/stat301-2-2024-winter/final-project-2-adacliu.git)

:::

## Prediction Problem

My prediction problem is: Can we predict whether a mushroom is edible or poisonous based on its physical characteristics? This is a classification problem. The variable to predict is the mushroom's edibility status, which can be categorized into two classes: edible (e) or poisonous (p).

## Data source

I plan to do my predictive model final project using the Mushroom Classification Dataset from Kaggle
^[Kaggle Dataset --- [Mushroom Classification](https://www.kaggle.com/datasets/uciml/mushroom-classification?resource=download)]. This data set was originally contributed the the UCI Machine Learning repository and contains descriptions of hypothetical samples corresponding to 23 species of gilled mushroom. Each species is classified as edible or poisonious.


## Why this data

This dataset will work well to predict if a mushroom is edible or not through a mushroom's physical characteristics. There are several motivations for pursing this problem in practicality, saftey, and personal curiosity. The ability to accurately predict whether a mushroom is edible or poisonous from easily observable characteristics could be a valuable tool for foragers, mushroom enthusiasts, and researchers. It enhances safety and knowledge in the field of mycology. Further, a reliable predictive model could potentially reduce the risk of mushroom poisoning by providing an additional tool for identifying poisonous varieties, especially with how foraging is becoming popular and mainstream.

I am personally interested in this since I have little experience with mushrooms in the wild but I enjoy cooking with them a lot. However, I have noticed that out of the thousands and thousands of mushroom species, we only eat around 5 on the daily. While I am not in the foraging community, I have seen posts come up about identifying mushrooms and finding it really interesting how people depend on what they look like to know if they are safe or not. Further, my parents come from China which has a rich history of using mushrooms in traditional medicine which has always made me wonder how people discovered their medicinal properties and how they learned which ones were safe, which ones were deadly, and which ones were medically helpful in specific doses.

## Data quality & complexity check

Blah blah blah

## Potential data issues

Blah blah blah

## Misc

Blah Blah
